apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrm-frontend
  namespace: hrm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hrm-frontend
  template:
    metadata:
      labels:
        app: hrm-frontend
    spec:
      containers:
        - name: frontend
          image: ringkokabiraj/hrm-frontend:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: hrm-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: hrm
spec:
  selector:
    app: hrm-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80