apiVersion: v1
kind: Secret
metadata:
  name: hrm-secret
  namespace: hrm
type: Opaque
stringData:
  DB_USER: root
  DB_PASSWORD: password
  MYSQL_ROOT_PASSWORD: password
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: securepassword123
