apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: hrm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.2
          ports:
            - containerPort: 3100
          args:
            - "-config.file=/etc/loki/local-config.yaml"
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: hrm
spec:
  selector:
    app: loki
  type: NodePort
  ports:
    - port: 3100
      targetPort: 3100
     