apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: hrm
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'backend'
        static_configs:
          - targets: ['backend:80']

      - job_name: 'frontend'
        static_configs:
          - targets: ['frontend:80']
